### ISSUE TITLE
convex_ineq_satisfied_gusto_jump

### ISSUE THREAD

**Issue by MarkMaBrain** [StanfordASL/GuSTO.jl#8]
In `scp_gusto.jl`,
`push!(convex_ineq_satisfied_vec, convex_ineq_satisfied_gusto_jump(new_traj, new_traj, SCPC, SCPP))`

Why is it `new_traj` instead of `SCPS.traj` for the second parameter?
Is it a typo?

**Comment by markcsie** [comment]
Just to clarify the difference between `new_traj` and `SCPS.traj`. 
If it's `new_traj`, it would be computing the constraints of the actual nonlinear functions, otherwise the linearized ones.
Which one is the intended one?

**Comment by acauligi** [comment]
Looks like that's a typo, thanks for pointing it out! Issue fixed [here](https://github.com/StanfordASL/GuSTO.jl/commit/089137f216accadd4d1fb6663edf1063b0fee2b6).

**Comment by markcsie** [comment]
Actually I read your paper, GuSTO: "Guaranteed Sequential Trajectory Optimization via Sequential Convex Programming", in which you used g_2 for the notation of the inequality, but it looks like g_2 is the nonlinear version as in eq.2 and eq.4.
It seems to me the linearized version is more reasonable. 
That's why I got confused, which one is the real typo or did I misunderstand something?
